title: "Z33DD's Blog"
author: "Z33DD"
description: "Good ideas don't require force"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# GitHub Pages config - https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Atom
atom:
  buildCommand:
    - jekyll
    - build
    - --this
  buildEnv:
    JEKYLL_ENV: production
  postDirs:
    - _posts
  defaultPostDir: _drafts

# Layout

sidebar: false               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: true                # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}
#  - {url: "/feed.xml", icon: rss, title: RSS}

external:                    # see http://fontawesome.com/icons
  - {title: Keybase, icon: keybase, url: "https://keybase.io/z33dd"}
  - {title: Github, icon: github, url: "https://github.com/z33dd"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
